apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: $(NAMESPACE)-storage                    # Storageları sınıflandırmak için kullanılıyor. Hepsi defaultta olunca karışıyor
  namespace: $(NAMESPACE)
provisioner: kubernetes.io/glusterfs
parameters:
  resturl: "http://192.168.10.100:8080" # No idea about what this is about
  restuser: ""
  secretNamespace: ""
  secretName: ""
allowVolumeExpansion: true