apiVersion: v1
kind: Service
metadata:
  name: geth-tx      # Servisin ismi
  namespace: geth # Yer alacağı namespace
  labels:
    app: geth     # Altında yer alacağı app
spec:
  ports:
  - port: 8545            
    name: node-tx


  clusterIP: 10.152.183.133 # Sabit ip veriyoruz ki conteinerlara bir ip verebilelim

  selector:
    app: geth
